---
downloads: ~/.ansible-downloads/

configure_homebrew: yes
configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: no
configure_zsh: yes

mcli_filepath: ~/Documents/Developer/Repositories/m-cli.forked.git/m

homebrew_clear_cache: true
homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'
homebrew_upgrade_all_packages: yes
homebrew_cask_accept_external_apps: false

#dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
#dotfiles_repo_accept_hostkey: no
#dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
#dotfiles_files:
#  - .bash_profile
#  - .gitignore
#  - .inputrc
#  - .osx
#  - .vimrc

homebrew_installed_packages: []
#  - ack
#  - ansible
#  - mackup
#  - neovim
#  - nnn
#  - pwgen
#  - rmtrash
#  - ssh-copy-id
#  - tmux
#  - vim
#  - watch
#  - zsh
#
repos:
  destination: ~/Documents/Developer/Repositories
  git:
    - repo: git@github.com:joshuaks/dotfiles.git
      version: development

    - repo: git@github.com:thegranddesign/m-cli.git
      name: m-cli.forked
      version: master

    - repo: https://github.com/dracula/zsh.git
      name: dracula.zsh
      version: master

    - repo: https://github.com/dracula/terminal-app.git
      name: dracula.terminal-app
      version: master

    - repo: https://github.com/robbyrussell/oh-my-zsh.git
      version: master

    - repo: https://github.com/gpakosz/.tmux.git
      name: oh-my-tmux
      version: master


homebrew_taps:
  - homebrew/bundle # required to install from brewfile
#
homebrew_cask_appdir: /Applications
homebrew_cask_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []


dockitems_to_remove:
  - Calendar
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences

dockitems_to_persist:
  - name: Downloads
    path: ~/Downloads

macos_configs:
  airport: 
    is_disconnect_on_logout: true
    non_preferred_networks_join_method: DoNothing
    preferred_networks_join_method: Ranked
    is_remember_recent_networks: true
    is_secure_ad_hoc_networks: true
    is_secure_change_networks: true
    is_secure_wifi_toggle: true
  is_animations: 
    mail: true
    inputs: true
    finder: true
    fullscreen: true
    windows: true
    quicklook: true
  appearance: 
    darkmode: true
    transparency: true
    antialiasthreshold: 8
    sidebariconsize: small
    maincolor: graphite
    highlightcolor: cantaloupe
  battery: 
  dashboard: 
    is_enabled: false
  datetime: 
    is_24_clock: true
    usentpserver: true
    ntpserver: time.apple.com
    international: false
    menubarformat: HH:MM:ss
  is_debugmode: false
  dialog: 
    is_autoexpand_dialogs: true
  dir: 
    dirs_to_hide: []
    dirs_to_show: []
  disk: 
  diskimages: 
  diskutility: 
  display: 
    is_auto_brightness: true
  filevault: 
  fullscreen: 
  group: 
  hotcorners: 
  info: 
  itunes: 
  keyboard: 
  launchpad: 
  locale: 
  location: 
  lock: 
  missioncontrol: 
  mouse: 
  network: 
  nosleep: 
  notification: 
  power: 
  printer: 
  restart: 
  safeboot: 
  screencapture: 
  scrolling: 
  shutdown: 
  sleep: 
  sound: 
  spotlight: 
  system: 
  tooltip: 
  update: 
  user: 
  volume: 
  vpn: 
  wallpaper: 
  windows: 
  airdrop:
    is_only_wifi: true
  bluetooth:
    is_on: true
  dns:
    is_flush: true
  general:
    is_sidebar_icon_size_small: true
    is_quit_printer_app_when_done: true
    is_are_you_sure_app_dialog: false
    is_help_viewer_non_floating: true
    is_restart_on_system_freeze: true
    is_auto_capitalization: false
    is_smart_dashes: false
    is_auto_period_substitution: false
    is_smart_quotes: false
    is_autocorrect: false
    is_enable_key_repeat: true
  finder:
    is_show_hidden_files: false
    is_show_file_extensions: true
    is_show_desktop: false
    is_show_path: true
    new_finder_window_location: ~/Documents
    desktop:
      is_show_external_hard_drives: false
      is_show_hard_drives: false
      is_show_mounted_servers: false
      is_show_removable_media: false
    is_keep_folders_on_top: true
    is_file_extension_change_warning: false
    is_springload_directories: true
    is_delay_springload_directories: true
    is_open_finder_on_volume_mount: true
    is_empty_tash_warning: true
    show_directories: [ "/Volumes" ]
    hide_directories: []
    file_info_pane:
      general: true
      open_with: false
      sharing_and_permissions: false
  dock:
    is_autohide: true
    is_magnification: false
    position: left
    is_add_blank_space: false
    is_add_recent_items: false
    is_remove_all_items: true
    icon_size: 16
    minimize_effect: scale
    is_minimize_to_app_icon: true
    is_springload: true
    is_show_indicator_lights: false
    is_show_open_apps_only: false # this would hide ~/Downloads, etc
    is_animate_opening_applications: true
    is_mission_control_group_apps: false
    is_disable_dashboard: true
    is_show_dashboard_as_space: false
    is_hidden_apps_translucent: true
    is_launchpad_gesture: false
  privacy:
    is_universal_search: false
    is_suppress_search_suggestions: true
  safari:
    is_show_full_address: false
    is_remove_default_bookmarks: true
    is_open_safe_files: false
    is_show_favorites_bar: false
    is_show_sidebar_in_topsites: true
    is_debug_menu: false
    is_find_on_page_matches_word_starts_only: false # contains
    is_develop_menu: true
    is_autofill:
      contacts: false
      passwords: false
      credit_cards: false
      misc_forms: false
    is_warn_about_fraudulent_sites: true
    is_plugins: true
    is_java: false
    is_block_popups: true
    is_autoplay_videos: false
    is_do_not_track: true
    is_update_extensions_automatically: true
  mail:
    is_addresses_include_name_on_pasteboard: false
    is_inline_attachments: false
  terminal:
    is_secure_keyboard_entry: true
    is_prompt_on_quit: false
  time_machine:
    is_do_not_prompt_to_use_new_disks: true
  text_edit:
    is_use_plaintext_by_default: true
  app_store:
    is_auto_update_check: true
    is_check_for_updates_daily: true
    is_download_updates_in_background: true
    is_install_system_updates: true
    is_download_purchases_from_other_macs: false
    is_app_auto_update: true
  photos:
    is_open_on_device: false
  messages:
    is_emoji_substition: true
    is_smart_quotes: false
    is_spell_check: true
  misc:
    is_expand_save_panel_by_default: true
    is_expand_print_panel_by_default: false
    is_save_to_icloud_by_default: false
    wallpaper_filepath: /Library/Desktop Pictures/Solar Gradients.heic
    is_dark_mode: true
  firewall:
    is_enable: true
  flightmode:
    is_on: false
  gatekeeper:
    is_enable: true
  hostname:
    name: josh-rmbp-13.local
  ntp:
    is_enable: true
    time_server: time.apple.com
  notification_center:
    is_enable: true
  screensaver:
    is_ask_for_password: true
  services:
    to_load: []
    to_unload: [
      "/System/Library/LaunchAgents/com.apple.gamed.plist"
    ]
  timezone:
    name: America/New_York
  trash:
    is_empty: true
  updates:
    is_install_all: true
  wifi:
    is_on: true



  
