---
downloads: ~/.ansible-downloads/

configure_homebrew: yes
configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: no
configure_zsh: yes


homebrew_clear_cache: true
homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'
homebrew_upgrade_all_packages: yes
homebrew_cask_accept_external_apps: false

#dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
#dotfiles_repo_accept_hostkey: no
#dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
#dotfiles_files:
#  - .bash_profile
#  - .gitignore
#  - .inputrc
#  - .osx
#  - .vimrc

homebrew_installed_packages: []
#  - ack
#  - ansible
#  - mackup
#  - neovim
#  - nnn
#  - pwgen
#  - rmtrash
#  - ssh-copy-id
#  - tmux
#  - vim
#  - watch
#  - zsh
#
homebrew_taps:
  - homebrew/bundle # required to install from brewfile
#
homebrew_cask_appdir: /Applications
homebrew_cask_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []


dockitems_to_remove:
  - Calendar
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences

dockitems_to_persist: []

mcli_configs:
  bluetooth:
    is_on: true
  dns:
    is_flush: true
  dock:
    is_change_show_delay: false
    show_delay: 0
    is_autohide: true
    is_magnification: false
    position: left
    is_add_blank_space: false
    is_add_recent_items: false
    is_remove_all_items: true
  finder:
    is_show_hidden_files: false
    is_show_file_extensions: true
    is_show_desktop: false
    is_show_path: true
  firewall:
    is_enable: true
  flightmode:
    is_on: false
  gatekeeper:
    is_enable: true
  hostname:
    name: josh-rmbp-13.local
  ntp:
    is_enable: true
    time_server: time.apple.com
  notification_center:
    is_enable: true
  screensaver:
    is_ask_for_password: true
  services:
    to_load: []
    to_unload: []
  timezone:
    name: America/New_York
  trash:
    is_empty: true
  updates:
    is_install_all: true
    #wallpaper:
      #is_set_wallpaper: false
      #filepath: /dev/null
  wifi:
    is_on: true
      #
defaults_write:
  general:
    is_sidebar_icon_size_small: true
    is_quit_printer_app_when_done: true
    is_are_you_sure_app_dialog: false
    is_help_viewer_non_floating: true
    is_restart_on_system_freeze: true
    is_auto_capitalization: false
    is_smart_dashes: false
    is_auto_period_substitution: false
    is_smart_quotes: false
    is_autocorrect: false
    is_enable_key_repeat: true
  finder:
    new_finder_window_location: ~/Documents
    desktop:
      is_show_external_hard_drives: false
      is_show_hard_drives: false
      is_show_mounted_servers: false
      is_show_removable_media: false
    is_keep_folders_on_top: true
    is_file_extension_change_warning: false
    is_springload_directories: true
    is_delay_springload_directories: true
    is_open_finder_on_volume_mount: true
    is_empty_tash_warning: true
    show_directories: [ "/Volumes" ]
    hide_directories: []
    file_info_pane:
      general: true
      open_with: false
      sharing_and_permissions: false

  
