---

- name: Remove items from Dock
  shell: "dockutil --remove '{{ item }}'"
  ignore_errors: true
  with_items: "{{ dockitems_to_remove }}"

- name: Add items to dock
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: "{{ dockitems_to_persist }}"

- name: Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  when: item.pos is defined
  with_items: "{{ dockitems_to_persist }}"

- name: Dock - Show delay
  command: "m dock showdelay {{ macos_configs.dock.show_delay }}"
  when: macos_configs.dock.show_delay is defined
  retries: 10
  delay: 2
  register: result
  until: result.rc == 0

- name: Dock - Show or hide
  command: "m dock autohide {{ 'YES' if macos_configs.dock.is_autohide else 'NO' }}"
  retries: 10
  delay: 2
  register: result
  until: result.rc == 0

- name: Dock - Enable or disable magnification
  command: "m dock magnification {{ 'YES' if macos_configs.dock.is_magnification else 'NO' }}"
  retries: 10
  delay: 2
  register: result
  until: result.rc == 0

- name: Dock - Set position (BOTTOM/LEFT/RIGHT)
  command: "m dock position {{ macos_configs.dock.position }}"
  retries: 10
  delay: 2
  register: result
  until: result.rc == 0

- name: Dock - Add blank space
  command: m dock addblankspace
  when: macos_configs.dock.is_add_blank_space
  retries: 10
  delay: 2
  register: result
  until: result.rc == 0

- name: Dock - Add recent items
  command: m dock addrecentitems
  when: macos_configs.dock.is_add_recent_items
  retries: 10
  delay: 2
  register: result
  until: result.rc == 0

- name: Dock - Set icon size
  command: "defaults write com.apple.dock tilesize -int {{ macos_configs.dock.icon_size }}"
  when: macos_configs.dock.icon_size is defined

- name: Dock - Change minimize/maximize window effect
  command: "defaults write com.apple.dock mineffect -string '{{ macos_configs.dock.minimize_effect }}'"

- name: Dock - Minimize windows into their application’s icon
  command: "defaults write com.apple.dock minimize-to-application -bool {{ macos_configs.dock.is_minimize_to_app_icon }}"

- name: Dock - Enable spring loading for all items
  command: "defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool {{ macos_configs.dock.is_springload }}"

- name: Dock - Show indicator lights for open applications
  command: "defaults write com.apple.dock show-process-indicators -bool {{ macos_configs.dock.is_show_indicator_lights }}"

- name: Dock - Don’t animate opening applications from the Dock
  command: "defaults write com.apple.dock launchanim -bool {{ macos_configs.dock.is_animate_opening_applications }}"

- name: Dock - Make Dock icons of hidden applications translucent
  command: "defaults write com.apple.dock showhidden -bool {{ macos_configs.dock.is_hidden_apps_translucent }}"

