---
- name: clean homebrew
  command: brew cleanup -s

- name: get homebrew cache location(s)
  command: brew --cache
  register: brew_cache_directories

- name: clean homebrew cache directories
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ brew_cache_directories.stdout_lines }}"

  #- name: clean homebrew cache
  #command: rm -rf "$(brew --cache)"

- name: check homebrew health
  command: brew doctor

- name: check homebrew for missing dependencies
  command: brew missing
