---
- name: add dracula theme to terminal.app (must set as default manually)
  command: open ~/Documents/Developer/Repositories/dracula.terminal-app.git/Dracula.terminal
  changed_when: false
  when: "'Dracula' not in terminal_theme.stdout"<Paste>

- name: Ensure dracula Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.Terminal 'Default Window Settings' -string 'Dracula'
    - defaults write com.apple.Terminal 'Startup Window Settings' -string 'Dracula'
  changed_when: false
  when: "'Dracula ansi' not in terminal_theme.stdout"

- name: symlink dracula theme
  file:
    src: ~/Documents/Developer/Repositories/dracula.zsh.git/dracula.zsh-theme
    dest: "{{ lookup('env','ZSH') }}/themes/dracula.zsh-theme"
    state: link


- name: symlink oh-my-tmux config
  file:
    src: ~/Documents/Developer/Repositories/oh-my-tmux.git/.tmux.conf
    dest: "{{ lookup('env','HOME') }}/.tmux.conf"
    state: link

