---
- name: Create symbolic link for Brewfile
  file:
    src: ~/.Brewfile
    dest: ~/Brewfile
    state: link

- name: Create symbolic link for m-cli
  file:
    src: ~/Documents/Developer/Repositories/m-cli.forked.git/m
    dest: ~/bin/m
    state: link

