---

- name: Sign in
  shell: eval $(op signin)

- name: Get me.id_rsa
  onepassword_facts:
    search_terms: 
      - name: me.id_rsa
        field: document
      - name: me.id_rsa.pub
        field: document
      - name: work.id_rsa
        field: document
      - name: work.id_rsa.pub
        field: document
  register: lookup_results
  no_log: true   # Don't want to log the secrets to the console!

- name: Write keys to disk
  copy:
    content: "{{ item.value.document }}\n"
    dest: "~/.ssh/{{ item.key }}"
  with_items: "{{ lookup_results['ansible_facts']['onepassword'] | dict2items }}"

