---
- name: create vim-plug directory
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: install vim-plug for nvim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: install plugins
  command: nvim -E -s -c "source {{ lookup('env','HOME') }}/.config/nvim/init.vim" -c PlugInstall! -c qa
  ignore_errors: yes 

- name: upgrade vim-plug
  command: nvim -E -s -c "source {{ lookup('env','HOME') }}/.config/nvim/init.vim" -c PlugUpgrade! -c qa
  ignore_errors: yes 

- name: update plugins
  command: nvim -E -s -c "source {{ lookup('env','HOME') }}/.config/nvim/init.vim" -c PlugUpdate! -c qa
  ignore_errors: yes 

- name: clean plugins
  command: nvim -E -s -c "source {{ lookup('env','HOME') }}/.config/nvim/init.vim" -c PlugClean! -c qa
  ignore_errors: yes 

