
- name: git - clone repos
  git:
    repo: "{{ item.repo }}" 
    dest: "{{ repos.destination }}/{{ item.repo.split('/') | last }}"
    version: "{{ item.version }}"
  when: item.name is undefined
  with_items: "{{ repos.git }}"

- name: git - clone repos
  git:
    repo: "{{ item.repo }}" 
    dest: "{{ repos.destination }}/{{ item.name }}.git"
    version: "{{ item.version }}"
  when: item.name is defined
  with_items: "{{ repos.git }}"

