

## m-cli: Mission Control #################################################
#- name: Mission Control -
#  command: "m {{ macos_configs. }}"
- name: Dock - Speed up Mission Control animations
  command: "defaults write com.apple.dock expose-animation-duration -float {{ macos_configs.dock.mission_control_speed }}"
  when: macos_configs.dock.mission_control_speed is defined

- name: Dock - Don’t group windows by application in Mission Control
  command: "defaults write com.apple.dock expose-group-by-app -bool {{ macos_configs.dock.is_mission_control_group_apps }}"

