---

- name: Remove items from Dock
  shell: "dockutil --remove '{{ item }}'"
  ignore_errors: true
  with_items: "{{ dockitems_to_remove }}"

- name: Add items to dock
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: "{{ dockitems_to_persist }}"

- name: Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  when: item.pos is defined
  with_items: "{{ dockitems_to_persist }}"

- import_tasks: ./_mcli_wrapper.yml
  vars:
    name: Dock - Show delay
    module: dock
    parameter: showdelay
    value: "{{ macos_configs.dock.show_delay }}"

- import_tasks: ./_mcli_wrapper.yml
  vars:
    name: Dock - Show or hide
    module: dock
    parameter: autohide
    value: "{{ 'YES' if macos_configs.dock.is_autohide else 'NO' }}"

- import_tasks: ./_mcli_wrapper.yml
  vars:
    name: Dock - Enable or disable magnification
    module: dock
    parameter: magnification
    value: "{{ 'YES' if macos_configs.dock.is_magnification else 'NO' }}"

- import_tasks: ./_mcli_wrapper.yml
  vars:
    name: Dock - Set position (BOTTOM/LEFT/RIGHT)
    module: dock
    parameter: position
    value: "{{ macos_configs.dock.position }}"

- import_tasks: ./_mcli_wrapper.yml
  vars:
    name: Dock - Add blank space
    module: dock
    parameter: addblankspace
    value: "{{ macos_configs.dock.is_add_blank_space }}"

- import_tasks: ./_mcli_wrapper.yml
  vars:
    name: Dock - Add recent items
    module: dock
    parameter: addrecentitems
    value: "{{ macos_configs.dock.is_add_recent_items }}"

- import_tasks: ./_defaults_wrapper.yml
  vars:
    name: Dock - Set icon size
    module: com.apple.dock
    parameter: tilesize
    value_type: int
    value: "{{ macos_configs.dock.icon_size }}"

- import_tasks: ./_defaults_wrapper.yml
  vars:
    name: Dock - Set icon size
    module: com.apple.dock
    parameter: mineffect
    value_type: string
    value: "{{ macos_configs.dock.minimize_effect }}"

- import_tasks: ./_defaults_wrapper.yml
  vars:
    name: Dock - Set icon size
    module: com.apple.dock
    parameter: minimize-to-application
    value_type: bool
    value: "{{ macos_configs.dock.is_minimize_to_app_icon }}"


- import_tasks: ./_defaults_wrapper.yml
  vars:
    name: Dock - Enable spring loading for all items
    module: com.apple.dock
    parameter: enable-spring-load-applications-on-all-items
    value_type: bool
    value: "{{ macos_configs.dock.is_springload }}"

- import_tasks: ./_defaults_wrapper.yml
  vars:
    name: Dock - Show indicator lights for open application
    module: com.apple.dock
    parameter: show-progress-indicators
    value_type: bool
    value: "{{ macos_configs.dock.is_show_indicator_lights }}"

- import_tasks: ./_defaults_wrapper.yml
  vars:
    name: Dock - Don’t animate opening applications from the Dock
    module: com.apple.dock
    parameter: launchanim
    value_type: bool
    value: "{{ macos_configs.dock.is_animate_opening_applications }}"

- import_tasks: ./_defaults_wrapper.yml
  vars:
    name: Dock - Make Dock icons of hidden applications translucent
    module: com.apple.dock
    parameter: showhidden
    value_type: bool
    value: "{{ macos_configs.dock.is_hidden_apps_translucent }}"
