

## m-cli: Finder #################################################
#- name: Finder -
#  command: "m {{ macos_configs. }}"
#- name: Finder - Show or hide hidden files
#  command: "m finder showhiddenfiles {{ 'YES' if macos_configs.finder.is_show_hidden_files else 'NO' }}"
#  retries: 10
#  delay: 2

- import_tasks: ./_mcli_wrapper.yml
  vars:
    name: Finder - Show or hide hidden files
    module: finder
    parameter: showhiddenfiles
    value: "{{ 'YES' if macos_configs.finder.is_show_hidden_files else 'NO' }}"

- name: Finder - Show or hide file extensions
  command: "m finder showextensions {{ 'YES' if macos_configs.finder.is_show_file_extensions else 'NO' }}"
  retries: 10
  delay: 2
  register: result
  until: result.rc == 0

- name: Finder - Show or hide the Desktop
  command: "m finder showdesktop {{ 'YES' if macos_configs.finder.is_show_desktop else 'NO' }}"
  retries: 10
  delay: 2
  register: result
  until: result.rc == 0

- name: Finder - Show path
  command: "m finder showpath {{ 'YES' if macos_configs.finder.is_show_path else 'NO' }}"
  retries: 10
  delay: 2
  register: result
  until: result.rc == 0



  ################################################################################
  ## Finder                                                                      #
  ################################################################################

# For other paths, use `PfLo` and `file:///full/path/here/`
# defaults write com.apple.finder NewWindowTarget -string "PfDe"
# defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"
#- name: Set default location for new Finder windows
#  command: | 
#      defaults write com.apple.finder NewWindowTarget -string 'PfLo' \
#      && defaults write com.apple.finder NewWindowTargetPath -string file://{{ macos_configs.finder.new_finder_window_location }}
#  when: macos_configs.finder.new_finder_window_location is defined

- name: Finder - Show or hide external hard drives on desktop
  command: "defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool {{ macos_configs.finder.desktop.is_show_external_hard_drives}}"

- name: Finder - show or hide hard drives on desktop
  command: "defaults write com.apple.finder ShowHardDrivesOnDesktop -bool {{ macos_configs.finder.desktop.is_show_hard_drives }}"

- name: Finder - Show or hide mounted servers on desktop
  command: "defaults write com.apple.finder ShowMountedServersOnDesktop -bool {{ macos_configs.finder.desktop.is_show_mounted_servers }}"

- name: Finder - Show or hide removable media on desktop
  command: "defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool {{ macos_configs.finder.desktop.is_show_removable_media }}"

  ## Finder: show hidden files by default
  ##defaults write com.apple.finder AppleShowAllFiles -bool true
  #
  #- name: Finder - show all filename extensions
  #  command: defaults write NSGlobalDomain AppleShowAllExtensions -bool true
  #
  #- name: Finder - show status bar
  #  command: defaults write com.apple.finder ShowStatusBar -bool false
  #
  #- name: Finder - show path bar
  #  command: defaults write com.apple.finder ShowPathbar -bool false
  #
  #- name: Display full POSIX path as Finder window title
  #  command: defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
  #
- name: Finder - Keep folders on top when sorting by name
  command: "defaults write com.apple.finder _FXSortFoldersFirst -bool {{ macos_configs.finder.is_keep_folders_on_top }}"

  #- name: Finder - When performing a search, search the current folder by default
  #command: defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
  #
- name: Finder - Disable the warning when changing a file extension
  command: "defaults write com.apple.finder FXEnableExtensionChangeWarning -bool {{ macos_configs.finder.is_file_extension_change_warning }}"
 
- name: Finder - Enable spring loading for directories
  command: "defaults write NSGlobalDomain com.apple.springing.enabled -bool {{ macos_configs.finder.is_springload_directories }}"

- name: Finder - Remove the spring loading delay for directories
  command: defaults write NSGlobalDomain com.apple.springing.delay -float 0
  when: not macos_configs.finder.is_delay_springload_directories

  #- name: Avoid creating .DS_Store files on network or USB volumes
  #  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true \
  #        && defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
  #
  #    # Disable disk image verification
  #    # defaults write com.apple.frameworks.diskimages skip-verify -bool true
  #    # defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
  #    # defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true
  #
- name: Finder - Automatically open a new Finder window when a (read-only) volume is mounted
  command: "defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool {{ macos_configs.finder.is_open_finder_on_volume_mount }}"

- name: Finder - Automatically open a new Finder window when a (read-write) volume is mounted
  command: "defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool {{ macos_configs.finder.is_open_finder_on_volume_mount }}"

- name: Finder - Automatically open a new Finder window when a (removable) volume is mounted
  command: "defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool {{ macos_configs.finder.is_open_finder_on_volume_mount }}"
  #    # Show item info near icons on the desktop and in other icon views
  #    # /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
  #    # /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
  #    # /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
  #
  #    # Show item info to the right of the icons on the desktop
  #    # /usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist
  #
  #    # Enable snap-to-grid for icons on the desktop and in other icon views
  #    # /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
  #    # /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
  #    # /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
  #
  #    # Increase grid spacing for icons on the desktop and in other icon views
  #    # /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
  #    # /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
  #    # /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
  #
  #    # Increase the size of icons on the desktop and in other icon views
  #    # /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
  #    # /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
  #    # /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
  #
  #    # Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
  #- name: Use list view in all Finder windows by default
  #  command: defaults write com.apple.finder FXPreferredViewStyle -string "clmv"
  #
- name: Finder - Disable the warning before emptying the Trash
  command: "defaults write com.apple.finder WarnOnEmptyTrash -bool {{ macos_configs.finder.is_empty_tash_warning }}"

  #    # Enable AirDrop over Ethernet and on unsupported Macs running Lion
  #    # defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

- name: Finder - Show specified hidden folders
  command: "chflags nohidden {{ item }}"
  become: true
  with_list: "{{ macos_configs.finder.show_directories }}"

- name: Finder - Hide specified visible folders
  command: "chflags nohidden {{ item }}"
  become: true
  with_list: "{{ macos_configs.finder.hide_directories }}"
  
 
- name: "Finder - Expand File Info panes (General, Open with, Sharing & Permissions)"
  command: |
      defaults write com.apple.finder FXInfoPanesExpanded -dict \
            General -bool {{ macos_configs.finder.file_info_pane.general }} \
            OpenWith -bool {{ macos_configs.finder.file_info_pane.open_with }} \
            Privileges -bool {{ macos_configs.finder.file_info_pane.sharing_and_permissions }}

  
