---

## m-cli: debug mode #################################################
#- name: Debug mode -
#  command: "m {{ macos_configs. }}"


## m-cli: dialog #################################################
#- name: Dialog -
#  command: "m {{ macos_configs. }}"


## m-cli: dirs #################################################
#- name: Dirs -
#  command: "m {{ macos_configs. }}"

## m-cli: Full Screen #################################################
#- name: Full Screen -
#  command: "m {{ macos_configs. }}"


#################################################################################
### General UI/UX                                                               #
#################################################################################

- name: General - Set sidebar icon size to small
  command: "defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int {{ 1 if macos_configs.general.is_sidebar_icon_size_small else 3 }}"

- name: General - Automatically quit printer app once the print jobs complete
  command: "defaults write com.apple.print.PrintingPrefs 'Quit When Finished' -bool {{ macos_configs.general.is_quit_printer_app_when_done }}"

- name: General - Disable the “Are you sure you want to open this application?” dialog
  command:  "defaults write com.apple.LaunchServices LSQuarantine -bool {{ macos_configs.general.is_are_you_sure_app_dialog }}"

- name: General - Remove duplicates in the “Open With” menu (also see `lscleanup` alias)
  command: /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

  #- name: Disable the crash reporter
  #command:  defaults write com.apple.CrashReporter DialogType -string "none"

- name: General - Set Help Viewer windows to non-floating mode
  command: "defaults write com.apple.helpviewer DevMode -bool {{ macos_configs.general.is_help_viewer_non_floating }}"
  #
- name: General - Restart automatically if the computer freezes
  command: "systemsetup -setrestartfreeze {{ 'on' if macos_configs.general.is_restart_on_system_freeze else 'off' }}"

- name: General - Disable automatic capitalization as it’s annoying when typing code
  command: "defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool {{ macos_configs.general.is_auto_capitalization }}"

- name: General - Disable smart dashes as they’re annoying when typing code
  command: "defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool {{ macos_configs.general.is_smart_dashes }}"

- name: General - Disable automatic period substitution as it’s annoying when typing code
  command: "defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool {{ macos_configs.general.is_auto_period_substitution }}"

- name: General - Disable smart quotes as they’re annoying when typing code
  command: "defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool {{ macos_configs.general.is_smart_quotes }}"

- name: General - Disable auto-correct
  command: "defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool {{ macos_configs.general.is_autocorrect }}"

################################################################################
## Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
################################################################################

- name: General - Disable press-and-hold for keys in favor of key repeat
  command: "defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool {{ not macos_configs.general.is_enable_key_repeat }}"


################################################################################
## Screen                                                                      #
################################################################################
#- name: Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
#  command: defaults write com.apple.screencapture type -string "png"

  #- name: Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
  #command: defaults write NSGlobalDomain AppleFontSmoothing -int 1


################################################################################
## Dock, Dashboard, and hot corners                                            #
################################################################################
  #    # Add a spacer to the left side of the Dock (where the applications are)
  #    #defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type="spacer-tile";}'
  #    # Add a spacer to the right side of the Dock (where the Trash is)
  #    #defaults write com.apple.dock persistent-others -array-add '{tile-data={}; tile-type="spacer-tile";}'
  #
  #    # Hot corners
  #    # Possible values:
  #    #  0: no-op
  #    #  2: Mission Control
  #    #  3: Show application windows
  #    #  4: Desktop
  #    #  5: Start screen saver
  #    #  6: Disable screen saver
  #    #  7: Dashboard
  #    # 10: Put display to sleep
  #    # 11: Launchpad
  #    # 12: Notification Center
  #    # Top left screen corner → Mission Control
  #    # defaults write com.apple.dock wvous-tl-corner -int 2
  #    # defaults write com.apple.dock wvous-tl-modifier -int 0
  #    # Top left screen corner → Notification Center
  #    #defaults write com.apple.dock wvous-tl-corner -int 12
  #    #defaults write com.apple.dock wvous-tl-modifier -int 0
  #
  #    # Top right screen corner → Desktop
  #    # defaults write com.apple.dock wvous-tr-corner -int 4
  #    # defaults write com.apple.dock wvous-tr-modifier -int 0
  #    # Bottom left screen corner → Start screen saver
  #    # defaults write com.apple.dock wvous-bl-corner -int 5
  #    # defaults write com.apple.dock wvous-bl-modifier -int 0
  #
#
################################################################################
## Address Book, Dashboard, iCal, TextEdit, and Disk Utility                   #
################################################################################
#
#    # Enable the debug menu in Address Book
#    # defaults write com.apple.addressbook ABShowDebugMenu -bool true
#
#    # Enable Dashboard dev mode (allows keeping widgets on the desktop)
#    # defaults write com.apple.dashboard devmode -bool true
#
#    # Enable the debug menu in iCal (pre-10.8)
#    # defaults write com.apple.iCal IncludeDebugMenu -bool true
#
- name: Use plain text mode for new TextEdit documents
  command: "defaults write com.apple.TextEdit RichText -int {{ 0 if macos_configs.text_edit.is_use_plaintext_by_default else 1 }}"
#

################################################################################
## More...                                                                      #
################################################################################
- name: Misc - Expand save panel by default
  command: "defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool {{ macos_configs.misc.is_expand_save_panel_by_default }}"

- name: Misc - Expand print panel by default
  command: "defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool {{ macos_configs.misc.is_expand_print_panel_by_default }}"

- name: Misc - Save to disk (not to iCloud) by default
  command: "defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool {{ macos_configs.misc.is_save_to_icloud_by_default }}"

- name: Misc - Set background to Solar Gradients
  command: osascript -e 'tell application "Finder" to set desktop picture to POSIX file "{{ macos_configs.misc.wallpaper_filepath }}"'
